### ISSUE TITLE
Interpolation not as expected.

### ISSUE THREAD

**Issue by o4sis** [thomersch/openweathermap_exporter#1]
Great job on the Openweather exporter. I have copied it down in my prometheus Lab and am trying to work out some kinks. I'm having an issue where the values on the graph are not interpolating as expected. As you can see on the image, the values are dropping down to zero which seems unexpected. By looking at the image below could you point me in the right direction to help address issue?

![image](https://cloud.githubusercontent.com/assets/21317652/18063111/4dfc201e-6def-11e6-8f76-83139f3563fb.png)

**Comment by thomersch** [comment]
Thanks for reporting :)

I had the same issue, although not so frequently. My guess is that the API delivers empty results from time to time. Probably I should add some mitigation for this. I'll let you know when I update the logic.

**Comment by o4sis** [comment]
Thanks for quick reply. The issue is now resolved. The fix is to scrape more often. My original configuration set the openweather scrape to happen every 600s. This lead to a staleness issue. One of the Prometheus devs let me know to not scrape at intervals longer than 300s.
